name: papers
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=19.2.3
  - ipython=7.8.0
  - pip:
    - bibtexparser==1.1.0
    - click==7.0
    - colorama==0.4.1
    - inquirer==2.6.3
    - pyyaml==5.1.2
    - requests==2.22.0
